# the application uses cloud config
# the values here are only used during testing

server:
  port: 8110
security:
  require-ssl: false
  ignored:
    - "/**"

domains.access.control.allow.origin: "*"

logging:
  level:
    root: INFO
    org.apache.http: WARN
    com.netflix: WARN
    org.springframework.security: INFO
    com.netflix.discovery.DiscoveryClient: OFF

# default to h2 database
spring:
  profiles:
    include: h2

  main:
    show-banner: false

---
# use H2 database
spring:
  profiles: h2

  datasource:
    url: jdbc:h2:mem:tempdb;MODE=oracle;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  jpa:
    database: H2
    show-sql: false
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

flyway:
  enabled: true
  locations: db/migration/h2

management:
  security:
    enabled: false


