branches:
  only:
    - master
    - /^deploy-.*$/

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - jq

language: java

jdk:
  - oraclejdk7

maven:
  version: 3.2.1

script:
  - jdk_switcher use oraclejdk7
  - mvn clean install -Pdocker -DuseGitCommitId

after_success:
  - docker images

