branches:
  only:
    - master
    - /^deploy-.*$/

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - jq

language: java

jdk:
  - oraclejdk8

maven:
  version: 3.2.1

install:
  - mvn clean install -DskipTests

script:
  - jdk_switcher use oraclejdk8
  - mvn test

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - mvn clean package -Pdocker -DpushImage
  - docker images

