branches:
  only:
    - master
    - /^deploy-.*$/

sudo: false

addons:
  apt:
    packages:
    - jq

language: java

jdk:
  - oraclejdk8

maven:
  version: 3.2.1

script:
  - jdk_switcher use oraclejdk8
  - mvn clean install

