---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: web
  selector:
    name: web

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
spec:
  replicas: 1
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web
        image: sloppycoder/ibank-web
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080

