---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    name: webapp

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  replicas: 1
  selector:
    name: webapp
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - name: webapp
        image: sloppycoder/ibank-webapp
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: SPRING_PROFILES_ACTIVE
          value: "h2"
        - name: CONFIG_SERVER_URL
          value: "http://cloudsvr:8761"
        - name: EUREKA_HOST
          value: "cloudsvr"
        - name: JDBC_URL
          value: "jdbc:mysql://dbhost/profdb"
        - name: REDIS_HOST
          value: "redis"
        - name: AUTH_SERVER_URL
          value: "http://10.245.1.3:8080/uaa"
        - name: APP_MAIN_URL
          value: "http://10.245.1.3:8080/app"
        ports:
        - containerPort: 8110

