---
apiVersion: v1
kind: Service
metadata:
  name: authsvr
  labels:
    name: authsvr
spec:
  ports:
  - port: 19999
    targetPort: 19999
  selector:
    app: authsvr

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authsvr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authsvr
    spec:
      containers:
      - name: cloudsvr
        image: sloppycoder/infra-auth-server
        ports:
        - containerPort: 19999
