---
apiVersion: v1
kind: Service
metadata:
  name: cloudsvr
  labels:
    name: cloudsvr
spec:
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    app: cloudsvr

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudsvr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudsvr
    spec:
      containers:
      - name: cloudsvr
        image: sloppycoder/infra-cloud-server
        ports:
        - containerPort: 8761

