---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    name: httpd
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: httpd
  selector:
    name: httpd

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd
  labels:
    name: httpd
spec:
  replicas: 1
  selector:
    name: httpd
  template:
    metadata:
      labels:
        name: httpd
    spec:
      containers:
      - name: httpd
        image: us.gcr.io/guru-gce-app1/ibank-httpd
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080

