---
apiVersion: v1
kind: Service
metadata:
  name: profilesvc
  labels:
    name: profilesvc
spec:
  ports:
  - port: 8110
    targetPort: 8110
  selector:
    app: profilesvc

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: profilesvc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: profilesvc
    spec:
      containers:
      - name: profilesvc
        image: sloppycoder/ibank-profile-service
        ports:
        - containerPort: 8110
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: SPRING_PROFILES_ACTIVE
          value: "mysql"
        - name: CONFIG_SERVER_URL
          value: "http://cloudsvr:8761"
        - name: EUREKA_HOST
          value: "cloudsvr"
        - name: JDBC_URL
          value: "jdbc:mysql://mysql/profdb"
