#
# THIS CONFIGURATION DOES NOT WORK !!
# since compose create /etc/host entries with "_" in host names, which is considered invalid
# since Eureka discovery client cannot register with Eureka server
#
#
# requires docker 1.9 networking feature
#
# docker-compose --x-networking up
#
#

# redis is used to store session data
#redis:
#  image: redis

#authsvr:
#  image: sloppycoder/infra-auth-server
#  #command: "-Dspring.active.profiles=mysql"
#  ports:
#    - "19999:19999"

cloudsvr:
  image: sloppycoder/infra-cloud-server
  environment:
    EUREKA_HOST: compose_cloudsvr_1
  ports:
    - "8761:8761"

profilesvc:
  image: sloppycoder/ibank-profile-service
  #command: "-Dspring.active.profiles=mysql"
  environment:
    CONFIG_SERVER_URL: http://compose_cloudsvr_1:8761
    EUREKA_HOST: compose_cloudsvr_1
#
#cardsvc:
#  image: sloppycoder/ibank-card-service
#  #command: "-Dspring.active.profiles=mysql"
#  environment:
#    CONFIG_SERVER_URL: http://compose_cloudsvr_1:8761
#    EUREKA_URL: http://compose_cloudsvr_1:8761/eureka/
#
#webapp:
#  image: sloppycoder/ibank-webapp
#  #command: "-Dspring.active.profiles=mysql"
#  environment:
#    CONFIG_SERVER_URL: http://compose_cloudsvr_1:8761
#    EUREKA_HOST: compose_cloudsvr_1
#    REDIS_HOST: compose_redis_1
#    AUTH_SERVER_URL: http://192.168.99.100:19999/uaa
#    APP_MAIN_URL: http://192.168.99.100:8000/app
#  ports:
#    - "8000:8000"
