server:
  port: 8889

logging:
  level:
    root: INFO
    org.apache.http: WARN
    org.springframework.security: INFO

domains.access.control.allow.origin: "*"

security:
  require-ssl: false
  oauth2:
    client:
      accessTokenUri: http://localhost:19999/uaa/oauth/token
      userAuthorizationUri: http://localhost:19999/uaa/oauth/authorize
      # currently the auth-server uses user/password (instead of client_id, client_secret) to
      # authentication /oauth/token end point (which is incorrect?)
      clientId: user
      clientSecret: password
      # auth server uses header schema. use form for github.
      clientAuthenticationScheme: header

    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

spring:
  application:
    name: minima-webapp

flyway:
  enabled: false
  locations: . # having an invalid path will cause flyway to fail

management:
  security:
    enabled: false

