server:
  port: 8080

logging:
  level:
    root: INFO
    org.apache.http: WARN
    org.springframework.security: INFO

cors.allow.origin: "http://localhost:9000"

security:
  require-ssl: false
  ignored:
    - "/**"

spring:
  application:
    name: test-webapp

flyway:
  enabled: false
  locations: . # having an invalid path will cause flyway to fail

management:
  security:
    enabled: false

nfs.simulatorServlet.enabled: true
