server:
  port: 8000

logging:
  level:
    root: INFO
    org.apache.http: WARN
    com.netflix: WARN
    CustomerClient: FULL
    org.springframework.security: INFO

security:
  require-ssl: false
  ignored:
    - "/"

  oauth2:
    client:
      accessTokenUri: http://localhost:19999/uaa/oauth/token
      userAuthorizationUri: http://localhost:19999/uaa/oauth/authorize
      # ssoLogoutUrl below is custom property, not part of Spring
      ssoLogoutUrl: http://localhost:19999/uaa/logout?redirect=http://localhost:8000/ssologout
      # the credential below must be configured in authorization server.
      clientId: acme
      clientSecret: acmesecret
      # auth server uses header schema. use form for github.
      clientAuthenticationScheme: header

    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

domains.access.control.allow.origin: "*"

spring:
  application:
    name: web-app
