# the application uses cloud config
# the values here are only used during testing

server:
  port: 8120
security:
  require-ssl: false
  ignored:
    - "/**"

management:
  security:
    enabled: false


cors.allow.origin: "*"

logging:
  level:
    root: INFO
    org.apache.http: WARN
    com.netflix: WARN
    org.springframework.security: INFO
    com.netflix.discovery.DiscoveryClient: OFF

# default to h2 database
spring:
  profiles:
    include: h2

  main:
    banner-mode: OFF

nfs:
  ccms:
    card-customer-service:
      endpoint-url: http://no_host_/CardCustomerService

nfs.simulatorServlet.enabled: true

---
spring:
  profiles: h2

  datasource:
    url: jdbc:h2:mem:tempdb;MODE=oracle;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  jpa:
    database: H2
    show-sql: false
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

flyway:
  enabled: true
  locations: db/migration/h2

---
spring:
  profiles: mysql

  datasource:
    url: ${JDBC_URL:jdbc:mysql://localhost/carddb}
    username: cardsvc
    password: password

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: ""
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

flyway:
  enabled: true
  locations: db/migration/mysql
