server:
  port: 8761 # this is the well known port for Eureka

logging:
  level:
    root: WARN

security:
  require-ssl: false
  ignored:
    - "/**"
    - "/mappings"
    - "/trace"
    - "/health"
    - "/info"

spring:
  profiles:
    active: native

  main:
    banner-mode: OFF

  config:
    name: cloud-server

  cloud:
    config:
      server:
        prefix: /cloudconfig
#        git:
#          uri: .
        native:
          searchLocations: ${CLOUD_CONFIG_PATH:../config}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    leaseRenewalIntervalInSeconds: 30 # should be set to 30 for production

turbine:
  aggregator:
    clusterConfig: WEBAPP
  appConfig: webapp

---
spring:
  profiles: test

  cloud:
    config:
      server:
        prefix: /cloudconfig
        native:
          searchLocations: ./src/main/resources

---
spring:
  profiles: docker

  cloud:
    config:
      server:
        prefix: /cloudconfig
        native:
          searchLocations: /config
