server:
  port: 8761 # this is the well known port for Eureka

logging:
  level:
    root: WARN

security:
  require-ssl: false
  ignored:
    - "/**"
    - "/mappings"
    - "/trace"

spring:
  profiles:
    active: native

  config:
    name: configserver

  cloud:
    config:
      server:
        prefix: /cloudconfig
        native:
          searchLocations: ../config

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    leaseRenewalIntervalInSeconds: 5 # should be set to 30 for production

turbine:
  aggregator:
    clusterConfig: WEBAPP
  appConfig: webapp
