server:
  port: 8761 # this is the well known port for Eureka

logging:
  level:
    root: WARN

security:
  require-ssl: false
  ignored:
    - "/**"
    - "/mappings"
    - "/trace"
    - "/health"
    - "/info"

spring:
  profiles:
    active: git

  main:
    banner-mode: OFF

  config:
    name: cloudsvr

  cloud:
    config:
      server:
        prefix: /cloudconfig
        git:
          uri: https://github.com/sloppycoder/nfs_config.git

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    leaseRenewalIntervalInSeconds: 30 # should be set to 30 for production

turbine:
  aggregator:
    clusterConfig: WEBAPP
  appConfig: webapp

---
spring:
  profiles: test

  cloud:
    config:
      server:
        prefix: /cloudconfig
        native:
          searchLocations: ./src/main/resources

logging:
  level:
    root: ERROR

---
spring:
  profiles: local

  cloud:
    config:
      server:
        prefix: /cloudconfig
        native:
          searchLocations: ../nfs_config
