#
#
# docker-compose up
#

version: '2'

services:
  # redis is used to store session data
  redis:
    image: redis:3.0.5
    networks:
      - default

  authsvr:
    image: ${DOCKER_REGISTRY_PREFIX}/infra-auth-server
    networks:
      - default

  cloudsvr:
    image: ${DOCKER_REGISTRY_PREFIX}/infra-cloud-server
    environment:
      EUREKA_HOST: cloudsvr
    networks:
      - default

  profilesvc:
    image: ${DOCKER_REGISTRY_PREFIX}/ibank-profile-service
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      CONFIG_SERVER_URL: http://cloudsvr:8761
      EUREKA_HOST: cloudsvr
      JDBC_URL: jdbc:mysql://${MYSQL_HOST}/profdb
    networks:
      - default
    depends_on:
      - cloudsvr
      - authsvr

  cardsvc:
    image: ${DOCKER_REGISTRY_PREFIX}/ibank-card-service
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      CONFIG_SERVER_URL: http://cloudsvr:8761
      EUREKA_HOST: cloudsvr
      JDBC_URL: jdbc:mysql://${MYSQL_HOST}/carddb
    networks:
      - default
    depends_on:
      - cloudsvr
      - authsvr

  webapp:
    image: ${DOCKER_REGISTRY_PREFIX}/ibank-webapp
    environment:
      CONFIG_SERVER_URL: http://cloudsvr:8761
      AUTH_SERVER_URL: http://authsvr:19999/uaa
      EUREKA_HOST: cloudsvr
      REDIS_HOST: redis
      # below are for use in browser
      # so need external domain name or public IP
      PUBLIC_APP_URL: ${PUBLIC_BASE_URL}/app
      PUBLIC_AUTH_URL: ${PUBLIC_BASE_URL}/uaa
    networks:
      - default
    depends_on:
      - redis
      - cloudsvr
      - authsvr
      - profilesvc
      - cardsvc

  httpd:
    image: ${DOCKER_REGISTRY_PREFIX}/ibank-httpd
    networks:
      - default
    ports:
      - "8080:8080"
    depends_on:
      - cloudsvr
      - authsvr
      - webapp

